### ISSUE TITLE
AssertionError when running train.py

### ISSUE THREAD

**Issue by lxqpku** [YaoMarkMu/CtrlFormer-ICML2022#1]
Traceback (most recent call last):
  File "train.py", line 251, in <module>
    main()
  File "/home/username/.conda/envs/drq/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/home/username/.conda/envs/drq/lib/python3.7/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/home/username/.conda/envs/drq/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/home/username/.conda/envs/drq/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 217, in main
    cfg1.env = cfg1.envs[cfg1.env_index][0]
  File "/home/username/.conda/envs/drq/lib/python3.7/site-packages/omegaconf/listconfig.py", line 43, in __getitem__
    assert isinstance(index, (int, slice))
AssertionError

**Comment by YaoMarkMu** [comment]
Hello, sorry for the confusion.
The command
```
python3 train.py  batch_size=512 action_repeat=2 env_index=[0,1,2,3,4]
```
means that you can choose one env_index from 0-4, and it should be run as the form like

```
python3 train.py  batch_size=512 action_repeat=2 env_index=0
```

**Comment by lxqpku** [comment]
> Hello, sorry for the confusion. The command
> 
> ```
> python3 train.py  batch_size=512 action_repeat=2 env_index=[0,1,2,3,4]
> ```
> 
> means that you can choose one env_index from 0-4, and it should be run as the form like
> 
> ```
> python3 train.py  batch_size=512 action_repeat=2 env_index=0
> ```

Right, I didn't check the code  in details before, thank you!
